site_name: QueryStorm Docs
site_url: https://www.querystorm.com/docs2
nav:
    - Introduction: Introduction.md
    - Querying:
      - Overview: "Querying/Overview.md"
      - SQLite: "Querying/SQLite.md"
      - Databases: "Querying/Databases.md"
      - C# scripts: "Querying/CSharp.md"
    - Automating workbooks:
      - Overview: Automation\Overview.md
      - Automation with .Net: Automation\Automation_with_dotnet.md
      - Automation with SQL: Automation\Automation_with_SQL.md
      - Importing/exporting code: Automation\Import_export_project.md
    - Custom Excel functions:
      - Overview: Functions\Overview.md
      - Functions via .Net: Functions\Functions_via_DotNet.md
      - Functions via SQL: Functions\Functions_via_SQL.md
      - Publishing functions: Functions\Publishing_functions.md
      - Installing packages: Functions\Installing_packages.md
    - General topics:
      - IDE tips & ticks: General\IDE.md
      - SQL Preprocessor: General\Preprocessor.md
      - Project system: General\Project_system.md
      - Data context: General\Data_context.md
theme: material
extra_css:
  - css/baguetteBox.css
extra_javascript:
  - js/jquery-3.3.1.min.js
  - js/youtube.js
  - js/baguetteBox.js
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.keys