site_name: QueryStorm Docs
site_url: https://www.querystorm.com/docs2
nav:
    - Introduction: Introduction.md
    - Querying:
      - Overview: "Querying/Overview.md"
      - SQLite: "Querying/SQLite.md"
      - Databases: "Querying/Databases.md"
      - C# scripts: "Querying/CSharp.md"
    - Custom Excel functions:
      - Overview: Custom Excel functions\Overview.md
      - Functions via .Net: Custom Excel functions\Functions via DotNet.md
      - Functions via SQL: Custom Excel functions\Functions via SQL.md
      - Publishing functions: Custom Excel functions\Publishing functions.md
      - Installing packages: Custom Excel functions\5. Installing packages.md
    - Automating workbooks:
      - Overview: Automating workbooks\Overview.md
      - Automation with .Net: Automating workbooks\Automation with dotnet.md
      - SQL Commands: Automating workbooks\SQL Commands.md
    - General topics:
      - Preprocessor: General topics\Preprocessor.md
      - Project system: General topics\Project system.md
      - Data context: General topics\DataContext.md
      - Managing packages: General topics\Managing packages.md
theme: material
extra_css:
  - css/baguetteBox.css
extra_javascript:
  - js/jquery-3.3.1.min.js
  - js/youtube.js
  - js/baguetteBox.js
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.keys