name: DocumentationBuildDeploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip
        run: python -m pip install --upgrade pip
      
      - name: Install mkdocs
        run: |
          pip install mkdocs
          pip install mkdocs-material
      
      - name: Build docs
        run: mkdocs build
        
      - name: Install packages
        run: |
          sudo apt install lftp
          sudo apt install expect
          
      - name: FTP Deploy
        env:
          FTP_PWD: ${{ secrets.QS_FTP_PWD }}
        run: |
          echo Starting...
          unbuffer lftp -c "open -u thingieq,"$FTP_PWD" win19.mojsite.com; debug; set -a; mirror -R -v site querystorm.com/wwwroot/DocsTest"
          echo Done transferring files.
