name: DocumentationBuildDeploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip
        run: python -m pip install --upgrade pip
      
      - name: Install mkdocs
        run: |
          pip install mkdocs
          pip install mkdocs-material
      
      - name: Build docs
        run: mkdocs build
          
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
          ftp-server: win19.mojsite.com/thingieq/querystorm.com/wwwroot/DocsTest/
          # FTP account username
          ftp-username: thingieq
          # FTP account password
          ftp-password: ${{ secrets.QS_FTP_PWD }}
          # The local folder to copy, defaults to root project folder
          local-dir: site/
